version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: loadboard-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loadboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  backend-fastapi:
    build: ./backend-fastapi
    container_name: loadboard-backend-fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/loadboard_db
      DOMAIN_URL: ${DOMAIN_URL:-https://www.alazie.express}
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loadboard-frontend
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://www.alazie.express}
    depends_on:
      - backend-fastapi
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: