services:
  - type: web
    name: loadboard-ai
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - loadboard-ai.onrender.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html