name: Bug Report
description: Report a bug or issue with the LoadBoard AI platform
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (React/UI)
        - Backend (FastAPI)
        - Database (Supabase)
        - Authentication
        - Dispatch System
        - Payment Processing
        - Training Modules
        - Mobile/PWA
        - Deployment/Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System is unusable
        - High - Major functionality broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic problem
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - Browser and version (e.g., Chrome 120, Firefox 121)
        - Operating System (e.g., Windows 11, macOS 14, Ubuntu 22.04)
        - Device type (Desktop, Mobile, Tablet)
        - Screen resolution (if relevant)
      placeholder: |
        Browser: Chrome 120
        OS: Windows 11
        Device: Desktop
        Screen: 1920x1080
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Screenshots
      description: |
        If applicable, add screenshots, console logs, or error messages to help explain your problem.
        You can paste screenshots directly or provide console output.
      placeholder: Paste error logs or drag and drop screenshots here...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false
