blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/AlazieXGit/ai-logisticpowerboard/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/AlazieXGit/ai-logisticpowerboard#readme
    about: Read the documentation for setup and usage guides
  - name: 🔒 Security Issues
    url: https://github.com/AlazieXGit/ai-logisticpowerboard/security
    about: Report security vulnerabilities privately
