name: Documentation Update
description: Request improvements or report issues with documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please describe what needs to be updated or clarified.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs to be updated?
      options:
        - README
        - API Documentation
        - Setup/Installation Guide
        - Deployment Guide
        - User Guide
        - Developer Guide
        - Code Comments
        - Security Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: Describe what's missing, unclear, or incorrect in the current documentation.
      placeholder: "Example: The deployment guide is missing instructions for..."
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where in the documentation is this issue? (File path, section, URL)
      placeholder: "Example: /README.md, line 45 or https://..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: Describe the changes you'd like to see...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help update the documentation?
      options:
        - label: I am willing to submit a pull request to update the documentation
          required: false
