name: Feature Request
description: Suggest a new feature or enhancement for the LoadBoard AI platform
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component/Area
      description: Which part of the application should this feature be added to?
      options:
        - Frontend (React/UI)
        - Backend (FastAPI)
        - Database (Supabase)
        - Authentication
        - Dispatch System
        - Payment Processing
        - Training Modules
        - Mobile/PWA
        - Deployment/Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking current work
        - High - Important for upcoming work
        - Medium - Would be nice to have
        - Low - Future enhancement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative solutions you've considered...
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: Who will benefit from this feature and how?
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Benefit 3
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, screenshots, or links to similar implementations.
      placeholder: Drag and drop images or provide links...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, technical details, or information about the feature request.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Are you willing to contribute to implementing this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false
