name: General Issue
description: For issues that don't fit other categories
title: "[General]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide details about your issue below. If this is a bug report or feature request, consider using the specific templates instead.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question
        - Discussion
        - Task
        - Improvement
        - Refactoring
        - Performance
        - Testing
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and detailed description of the issue or topic.
      placeholder: Describe your issue in detail...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component (if applicable)
      description: Which part of the application does this relate to?
      options:
        - Frontend (React/UI)
        - Backend (FastAPI)
        - Database (Supabase)
        - Authentication
        - Dispatch System
        - Payment Processing
        - Training Modules
        - Mobile/PWA
        - Deployment/Infrastructure
        - Documentation
        - Testing
        - CI/CD
        - Not applicable
        - Other
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, code snippets, or relevant information.
      placeholder: Any additional details...
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria (if applicable)
      description: What needs to be done to consider this issue resolved?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false
