name: EAS Build and Update

on:
  push:
    branches: [main, master]
    paths:
      - 'src/**'
      - 'app.json'
      - 'eas.json'
      - 'package.json'
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - ios
          - android
          - all

jobs:
  eas-update:
    name: EAS Update
    runs-on: ubuntu-latest
    # Only run updates on push to main/master, not on PRs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "::warning::EXPO_TOKEN secret is not set. Please add it to GitHub Secrets."
            echo "::warning::See EAS_SETUP.md for instructions on creating an EXPO_TOKEN."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish EAS Update
        run: |
          eas update --branch production --message "Automated update from GitHub Actions" --non-interactive

  eas-build:
    name: EAS Build
    runs-on: ubuntu-latest
    # Only run on manual workflow dispatch
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "::error::EXPO_TOKEN secret is not set. Please add it to GitHub Secrets."
            echo "See EAS_SETUP.md for instructions on creating an EXPO_TOKEN."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build with EAS
        run: |
          PLATFORM="${{ github.event.inputs.platform }}"
          echo "Building for platform: $PLATFORM"
          eas build --platform $PLATFORM --profile production --non-interactive --no-wait

      - name: Build completion notice
        run: |
          echo "::notice::EAS build started. Check build status at https://expo.dev"
